CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE PRODUCT_TYPES (
    ID SERIAL PRIMARY KEY,
    UUID UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    NAME TEXT NOT NULL
);

CREATE TABLE PRODUCTS (
    ID SERIAL PRIMARY KEY,
    UUID UUID UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    NAME TEXT NOT NULL,
    PRODUCT_TYPE_ID BIGINT REFERENCES PRODUCT_TYPES(ID) NOT NULL,
    WEIGHT NUMERIC(3, 2)
);