CREATE TABLE PRODUCT_TYPES (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL
);

CREATE TABLE PRODUCTS (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL,
    PRODUCT_TYPE INTEGER REFERENCES PRODUCT_TYPES(ID) NOT NULL,
    WEIGHT NUMERIC(3, 2)
);